# This is a basic workflow to help you get started with Actions

name: Sync Deploy to Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "build-and-publish" ]


  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync_branchs:
    permissions:
      contents: write
    runs-on: ubuntu-latest


    steps:
      - name: Checkout build branch
        uses: actions/checkout@v4
        with:
          ref: build-and-publish
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure User
        run: | 
          git config user.name "Deploy Bot" 
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: build site
        run: |
          npm install
          ng build --output-path docs --base-href /YAML-Learning/ --configuration production

      - name: echo files 
        run: 
          ls

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/trello-clone/browser
          publish_branch: static-site

      - name: End
        run:
          echo "testing"
          echo "testing"



  



